config/routes.rb
Rails.application.routes.draw do

  get 'tweets/index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' } # ここを変更
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'tweets#index'

  resources :maps
  resources :blogs
  resources :users, only: [:show]

  # 管理画面のルーティング
  namespace :admin do
    resources :users, except: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/map.rb
# geocode uriのenv暫定対応
Dotenv.load

class Map < ApplicationRecord
  after_validation :geocode, if: :followerlocation_changed?

  belongs_to :user

  validates :followername, presence: true
  validates :followerlocation, presence: true

  private
  def geocode
    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.followerlocation.gsub(" ", "")+ "&key=" + ENV['google_map_API_key'])
    res = HTTP.get(uri).to_s
    response = JSON.parse(res)
    self.latitude = response["results"][0]["geometry"]["location"]["lat"] if response["results"].present?
    self.longitude = response["results"][0]["geometry"]["location"]["lng"] if response["results"].present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :maps, dependent: :delete_all
  has_many :blogs, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

         def self.find_for_oauth(auth)
          user = User.where(uid: auth.uid, provider: auth.provider).first
       
          unless user
            user = User.create(
              provider: auth.provider,
              uid:      auth.uid,
              name: auth.info.nickname,
              email:    User.dummy_email(auth),
              password: Devise.friendly_token[0, 20]
            )
          end
       
          user
        end
       
        private
       
      # ダミーのアドレスを用意
        def self.dummy_email(auth)
          "#{auth.uid}-#{auth.provider}@example.com"
        end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  # 追加開発用
  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to admin_users_path
  #   else
  #     render new_admin_user_path
  #   end
  # end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザーを編集しました"
    else
      render admin_users_path, notice: "ユーザーの編集に失敗しました"
    end
  end  

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice:"ユーザーの削除に成功しました"
    else
      redirect_to admin_users_path, notice:"ユーザーの削除に失敗しました"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_blog, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidを、blogのuser_idカラムに挿入する
    @user = @blog.user.name
    if @blog.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: t('view.blog_created!')
    else
      # 入力フォームを再描画します。
      render :new
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: t('view.blog_edited!')
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: t('view.blog_deleted!')
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_map, only: [:destroy]
  def index
    @maps = current_user.maps.where.not(latitude: nil)
  end

  def new
    @map = Map.new
  end

  def destroy
    @map.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:address, :latitude, :longitude)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :twitter

  def index
    if user_signed_in?
      #もし同じユーザー名のデータがある場合、紐づくフォロワーデータを全削除
      current_user.maps.delete_all if User.where(name: current_user.name).count >= 1

      followers = twitter.followers(current_user.name).take(20)
      # (current_user.name)
      # @followers.save!
      # redirect_to map_path

      # json = ActiveSupport::JSON.decode(followers)
      # json = JSON.parse(followers)
        # @maps = []

      followers.each do |data|
        map = Map.new(
          followername: data.name,
          followerlocation: data.location
        )
        # @maps << map
        map.user_id = current_user.id
        map.save
      end
      redirect_to maps_url
    end  
  end

  private
    def twitter
      client = Twitter::REST::Client.new do |config|
        config.consumer_key =ENV['twitter_API_key']
        config.consumer_secret =ENV['twitter_API_secret_key']
        config.access_token =ENV['twitter_access_token']
        config.access_token_secret =ENV['twitter_access_token_secret']
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 
 
  def twitter
    callback_from :twitter
  end
 
  private
 
  def callback_from(provider)
    provider = provider.to_s
 
    @user = User.find_for_oauth(request.env['omniauth.auth'])
 
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end  

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/admin/users/edit.html.erb
<h1><%= t('view.user_edit') %></h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%# form_withはmodelから送信先コントローラを自動指定するため、送りたいpathを明示的に指定する %>
<%= form_with(model: @user, local: true, url: admin_user_path ,method: :patch) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label t('view.admin') %>
  <%= f.check_box :admin, {} , "true", "false" %>

  <%= f.submit t('view.edit') %>
<% end %>

app/views/admin/users/index.html.erb
<h1><%= t('view.management_screeen') %></h1>

<div id=wrapper_admin>
  <table>
    <tr>
      <th><%= t('view.management_screen_name') %></th>
      <th><%= t('view.management_screen_authority') %></th>
    </tr>  

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      
      <td>
        <%if user.admin == true %>
          <% t('view.admin')%>
        <% else %>
          <% t('view.normal_user')%>
        <%end%>
      </td>
      
      <td><%= link_to t('view.edit'), edit_admin_user_path(user.id) %></td>
      <td><%= link_to t('view.delete'), admin_user_path(user.id), method: :delete %></td>
    </tr>
  <% end %>

  </table>
</div>

app/views/admin/users/new.html.erb
# 追加開発用
<%# <h1>Admin::Users#new</h1>
<p>Find me in app/views/admin/users/new.html.erb</p> %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %><%= t('view.errors_count')%></h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to t('view.back_to_blog_view'), blogs_path %>

app/views/blogs/index.html.erb
<h1><%= t('view.blog_view') %></h1>

<%if user_signed_in? %>
  <% if current_user.admin == true %>
    <%= link_to t('view.blog_post') , new_blog_path %>
  <% end %>
<% end %>

<div id="wrapper">
  <table>
    <tr>
      <th><%= t('view.title') %></th>
      <th><%= t('view.content') %></th>
      <th><%= t('view.auther') %></th>
    </tr>

  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.content %></td>
      <td><%= blog.user.name %></td>

    <%if user_signed_in? %>
      <% if current_user.admin == true %>  
        <td><%= link_to t('view.edit'), edit_blog_path(blog.id) %></td>
        <td><%= link_to t('view.delete'), blog_path(blog.id), method: :delete %></td>
      <% end %>
    <% end %>  
    </tr>
  <% end %>
  </table>
</div>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %><%= t('view.errors_count')%></h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to t('view.back_to_blog_view'), blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>followermap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <ul>
      <%if user_signed_in? %>
        <li><%= link_to 'map', maps_path %></li>
      <%end%>  
      <li><%= link_to 'blog', blogs_path %></li>
      <%if user_signed_in? %>
          <li><a><%=current_user.name%></a></li>
          <%if current_user.admin == true %>
            <li><%= link_to t('view.admin'), admin_users_path %></li>
          <%end%>

        <li><%= link_to t('view.my_page'), user_path(current_user.id) %></li>
        <li><%= link_to t('view.logout'), destroy_user_session_path, method: :delete %></li>

      <%else%>
        <li><%= link_to t('view.login'), new_user_session_path %></li>
      <%end%>
    </ul>
  </header>  

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  <footer>
    <p>© 2019 Copyright followermap.</p>
  </footer>

  </body>
</html>

app/views/maps/index.html.erb
<h1>Dashboard</h1>
<h2><%= t('view.about_dashboard')%></h2>

<script async defer
 src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%=ENV['google_map_API_key']%>&callback=initMap">
</script>


<!--マップ-->
<div id="map"></div>

<style type="text/css">
  #map { height: 400px;
    margin-left:auto;
    margin-right:auto;
    text-align:left;
    width: 80%;}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      var latlng = new google.maps.LatLng(36.30, 139.5);
      //デザイン
      var styles = [
           {
            stylers: [
             { "saturation": -95 },
             { "lightness": -20 }
            ]
           }
          ];
      //↓マップの初期設定値を記述
      var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5, //初期のマップの倍率 １－１８までで指定 数字が大きくなるとズームアップ
          styles: styles,
          center: latlng //地図の中心の指定
      });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

      //複数マーカー ここから
      <% @maps.each do |map| %>
      (function(){
        var contentString = "住所：<%= map.followerlocation %>"; 
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:{lat: <%= map.latitude %>, lng: <%= map.longitude %>},
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
          infowindow.open(map, marker, content);
        });
       })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<br>

<div id="wrapper">
  <table>
    <thead>
      <tr>
        <th><%= t('view.followerlocation') %></th>
        <th><%= t('view.Latitude') %></th>
        <th><%= t('view.Longitude') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @maps.each do |map| %>
        <tr>
          <td><%= map.followerlocation %></td>
          <td><%= map.latitude %></td>
          <td><%= map.longitude %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tweets/index.html.erb
<ul>
<%if user_signed_in? %>
  <li><%=current_user.email%></li>
  <li><%=current_user.name%></li>

  <li><%= link_to t('view.logout'), destroy_user_session_path, method: :delete %></li>
<%else%>
  <li><%= link_to t('view.login'), new_user_session_path %></li>
<%end%>
</ul>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= t('view.my_page')%></h1>
<p><%= t('view.user_name')%>:<%= @user.name %></p>